name: THANOS (EURUSD M5 every 15m)

permissions:
  contents: write

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

jobs:
  thanos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Print env & time
        run: |
          uname -a
          date -u

      - name: Fetch feeds (Pepperstone & TwelveData) with verbose logs
        run: |
          set -e
          mkdir -p data
          echo "Downloading Pepperstone..."
          curl -v -L --fail --retry 3 --retry-delay 2 -A "Mozilla/5.0" \
            'https://raw.githubusercontent.com/meryemmi2000-ui/eurusd-feeds/refs/heads/main/data/pepperstone.csv' \
            -o data/pepperstone.csv
          echo "Downloading TwelveData..."
          curl -v -L --fail --retry 3 --retry-delay 2 -A "Mozilla/5.0" \
            'https://raw.githubusercontent.com/meryemmi2000-ui/eurusd-feeds/refs/heads/main/data/twelvedata.csv' \
            -o data/twelvedata.csv
          echo "Files sizes:"
          wc -c data/*.csv || true
          date -u +"%Y-%m-%d %H:%M:%S UTC" > data/last_updated.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run THANOS analysis (safe)
        run: |
          python - <<'PY'
          import pandas as pd
          from pathlib import Path

          # Charger Pepperstone et TwelveData
          p = pd.read_csv("data/pepperstone.csv", sep=None, engine="python")
          t = pd.read_csv("data/twelvedata.csv", sep=";")

          print("Pepperstone:", p.head(3))
          print("TwelveData:", t.head(3))

          Path("data/thanos_summary.md").write_text("THANOS ran successfully ✅\n")
          PY

      - name: Commit results
        run: |
          git add data/*
          git commit -m "THANOS run" || true
          git push || true
